server:
  port: 8080

spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      driver-class-name: ${yiming1234.datasource.driver-class-name}
      url: jdbc:mysql://${yiming1234.datasource.host}:${yiming1234.datasource.port}/${yiming1234.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${yiming1234.datasource.username}
      password: ${yiming1234.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.yiming1234.NottinghamWall.entity, cn.yiming1234.NottinghamWall.dto
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

redis:
  host: ${yiming1234.redis.host}
  port: ${yiming1234.redis.port}
  password: ${yiming1234.redis.password}

logging:
  level:
    cn:
      yiming1234:
        mapper: debug
        service: info
        controller: info

yiming1234:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: yiming1234
    user-ttl: 7200000
    user-token-name: token
  alioss:
    endpoint: ${yiming1234.alioss.endpoint}
    access-key-id: ${yiming1234.alioss.access-key-id}
    access-key-secret: ${yiming1234.alioss.access-key-secret}
    bucket-name: ${yiming1234.alioss.bucket-name}
  wechat:
    appid: ${yiming1234.wechat.appid}
    secret: ${yiming1234.wechat.secret}