name: SpringBoot Built and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: ''
        servers: ''
    - name: Build with Maven
      run: mvn package -B -DskipTests --file backend/pom.xml
    - name: GH Release
      uses: softprops/action-gh-release@v2.0.6
      with:
        files: backend/wall-server/target/wall-server-*.jar
        name: Updated at 25/02/10
        tag_name: NottinghamWall-backend-v1.0
    - name: upload to server
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.SERVER_HOST}}
        username: ${{secrets.SERVER_USER}}
        password: ${{secrets.SERVER_PASSWORD}}
        port: 22
        source: "backend/wall-server/target/"
        target: ${{secrets.SERVER_PATH}}
